"""add foreign key from holdings.portfolio_id to portfolios.id

Revision ID: 2b8e4f5015de
Revises: ec523efb463d
Create Date: 2026-09-21 19:48:02.099980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8e4f5015de'
down_revision: Union[str, Sequence[str], None] = 'ec523efb463d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'holdings', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    # ### end Alembic commands ###
