"""create core portfolio tables

Revision ID: ec523efb463d
Revises: 
Create Date: 2026-09-12 15:41:36.300043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec523efb463d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_cost >= 0', name='ck_holding_average_cost_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_holding_quantity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', name='uq_holding_portfolio_ticker')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('max_position_weight', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('max_sector_weight', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('drift_threshold', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('target_volatility', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('risk_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cash_balance >= 0', name='ck_portfolio_cash_nonnegative'),
    sa.CheckConstraint('initial_capital >= 0', name='ck_portfolio_initial_capital_nonnegative'),
    sa.ForeignKeyConstraint(['risk_profile_id'], ['risk_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('invested_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('daily_return', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('cumulative_return', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.CheckConstraint("transaction_type IN ('BUY', 'SELL')", name='ck_transaction_type'),
    sa.CheckConstraint('fees >= 0', name='ck_transaction_fees_nonnegative'),
    sa.CheckConstraint('price >= 0', name='ck_transaction_price_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_transaction_quantity_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('portfolio_snapshots')
    op.drop_table('portfolios')
    op.drop_table('risk_profiles')
    op.drop_table('user_profiles')
    op.drop_table('holdings')
    # ### end Alembic commands ###
